version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
      - run:
          name: install-npm-wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
          paths:
          - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
        path: test-results.xml
        prefix: tests
      - store_artifacts:
        path: coverage
        prefix: coverage
      - store_test_results:
        path: test-results.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
