version: 2.1
executors:
  default:
    working_directory: ~/graphql-todo-sample
    docker:
      - image: circleci/node:12-stretch
commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Cache npm dependencies
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/graphql-todo-sample/node_modules
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run test
          command: yarn run test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
